### ISSUE TITLE
No space left on device after some days of usage

### ISSUE THREAD

**Issue by slash4** [jasonwyatt/docker-nginx-loadbalancer#7]
I experience a strange problem on a production server we configured as a load balancer using this image. Although the instance is configured not to write logs on the disk (access_log /dev/stdout;
    error_log /dev/stdout;) I can clearly see the disk on the docker host decreasing constantly until that point where there's not any space left and the loadbalancer becomes unresponsive. 

Do you experience the same problems while using this image intensively like us (I mean, 10K requests/min on peaks) ? Do you see a workaround ? Maybe `error_log /dev/null;` ?

Thanks ! Alex

**Comment by jasonwyatt** [comment]
I would definitely try to route the logs to /dev/null and see if it fixes
the problem..

On Mon, Mar 14, 2016 at 1:06 PM, CENTAR Alex notifications@github.com
wrote:

> I experience a strange problem on a production server we configured as a
> load balancer using this image. Although the instance is configured not to
> write logs on the disk (access_log /dev/stdout;
> error_log /dev/stdout;) I can clearly see the disk on the docker host
> decreasing constantly until that point where there's not any space left and
> the loadbalancer becomes unresponsive.
> 
> Do you experience the same problems while using this image intensively
> like us (I mean, 10K requests/min on peaks) ? Do you see a workaround ?
> Maybe error_log /dev/null; ?
> 
> Thanks ! Alex
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jasonwyatt/docker-nginx-loadbalancer/issues/7.

## 

Jason Feinstein

**Comment by slash4** [comment]
Yes it does :) 

Would you want me to do a PR for that ? I could add another ENV variable to set it to either dev/stdout or dev/null.

**Comment by jasonwyatt** [comment]
Sure, that sounds great, thanks!  If you could give the ENV variable a
default to stdout, that would be perfect.

On Mon, Mar 14, 2016 at 3:26 PM, CENTAR Alex notifications@github.com
wrote:

> Yes it does :)
> 
> Would you want me to do a PR for that ? I could add another ENV variable
> to set it to either dev/stdout or dev/null.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jasonwyatt/docker-nginx-loadbalancer/issues/7#issuecomment-196331274
> .

## 

Jason Feinstein

**Comment by slash4** [comment]
PR #8 fixes that. Thanks !
